### PR TITLE
following count more than X will be treated as fake account

### PR DESCRIPTION
**Pull request by donaldng**
For example this is obviously a fake account, but the follows/follower ratio is not more than 2, but merely 1.05.

```
13.01.2018_10:37 Getting user info : doctor_herbal20
13.01.2018_10:37 Checking user info..
13.01.2018_10:37 Follower : 6882
13.01.2018_10:37 Following : 7230
13.01.2018_10:37 Media : 198
```

### CODE REVIEW

**Comment by ugurozturk** [comment]
- Please dont stage and commit follows_db.db file.
- Squash your commits please

**Comment by donaldng** [comment]
@ugurozturk thanks for the pointers!

**Comment by ugurozturk** [comment]
Any news about this ?
- Also it would be good if the user can specify the number

**Comment by NodalPoint** [comment]
Would like to see this added as well.

**Comment by donaldng** [comment]
Sorry for late update. I've added a new parameter _fake_follows_limit_ to allow user to specify the fake account limit.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Pull request closed without merging**
