### PR TITLE
Modify auto_unlike function to process deleted medias

### PR DESCRIPTION
**Pull request by nickgryg**
This PR is inspired by [issue 2178](https://github.com/instabot-py/instabot.py/issues/2178)

1. Added possibility to process deleted from instagram medias. 
If media is deleted, we don't need to unlike it anymore, so we need to update database accordingly. This helps to prevent processing this medias every time we call auto_unlike() function.

2. Added more verbosity information to log output.

### CODE REVIEW

**Comment by yurilaaziz** [comment]
looks good to me.
Could you also review the other logging messages too to add more verbosity? 
Users continue to open an issue to do some ambiguity. 
I would like to have your suggestions about that too.

I will test and merge asap.
cc @dimisdas

**Comment by nickgryg** [comment]
I will do @yurilaaziz 
It will be another PR soon.

**Comment by yurilaaziz** [comment]
Thank you for the PR 
added to the mainstream

**Comment by nickgryg** [comment]
@yurilaaziz What do you mean by "added to the mainstream" if this PR was just closed and commit was not merged into master branch?

**Comment by yurilaaziz** [comment]
check the commit log please

**Comment by nickgryg** [comment]
@yurilaaziz I got it :) Thank you.

**Pull request closed without merging**
