### PR TITLE
Fixes for Unfollow whitelist feature

### PR DESCRIPTION
**Pull request by saphiresouldier**
Added a check/fix for the (rare but possible) case that the users mostly follows users that are on the whitelist and updated README.mp to reflect the whitelist feature/parameter.

### CODE REVIEW

**Comment by dadealer** [comment]
I think you need to set the counter back to zero after the bot breaks up. Or if I'm wrong?

**Comment by dadealer** [comment]
Sorry.   I was wrong. I build this in later

**Comment by saphiresouldier** [comment]
After thinking for a bit I decided it's better to completely abort the unfollow attempt if only whitelist users are chosen (threshold: 15 times for now). This change is implemented in the last commit

**Comment by polaroi8d** [comment]
Rebase the commits please.

**Comment by ChipWolf** [comment]
@polaroi8d no conflicts? Rebase from what?

**Comment by polaroi8d** [comment]
@ChipWolf sorry, wrong comment, this is for the other PR :) its my fault

**Comment by ChipWolf** [comment]
Can someone test this

**Comment by polaroi8d** [comment]
@ChipWolf you, for example?

**Comment by ChipWolf** [comment]
Refactor please.

**Comment by polaroi8d** [comment]
@ChipWolf Stop deleting my comments, please.

**Comment by polaroi8d** [comment]
@ChipWolf Really? You are so open sourced, bro.

**Comment by maxdid** [comment]
I need this feature. Could I help someone to test this?
Would be nice to have the possibility for a mode to unfollow all the following not in unfollow_whitelist

**Comment by ugurozturk** [comment]
We already have this feature

**Pull request closed without merging**
