### PR TITLE
Update readme. spelling and reorder.

### PR DESCRIPTION
**Pull request by JoshTristram**
I made a new logo
<a href="#InstaBot" title="Instabot.py Logo"></a>
Added the install guide to the top (more importent).

### CODE REVIEW

**Comment by ohld** [comment]
Nice logos dude https://github.com/instagrambot/instabot/blob/master/docs/img/tag%20instabot.png

**Comment by JoshTristram** [comment]
Removed logo.

**Comment by penarubah** [comment]
@JoshTristram LOL

**Comment by ChipWolf** [comment]
ai'ight

**Pull request merged**
