### PR TITLE
remove duplicated comment

### PR DESCRIPTION
**Pull request by ohld**
remove duplicated comment in generate_comment() function

### CODE REVIEW

**Comment by nivong** [comment]
👍

**Comment by Killerherts** [comment]
This is good on my systems

**Comment by polaroi8d** [comment]
Why this is a duplicate?

**Comment by nivong** [comment]
@polaroi8d because so so stylish is added 2 times.

**Comment by ChipWolf** [comment]
This comment is a huge gamechanger, the entire community will benefit from this innovative change. Thank you for your undue service @ohld, congratulations on this lifetime achievement.

**Pull request merged**
