### PR TITLE
Update instabot.py

### PR DESCRIPTION
**Pull request by maxkrivich**
fix this exception in win10 x64 python 2.7.13
Exception KeyError: KeyError(12172,) in <module 'threading' from 'C:\Python27\lib\threading.pyc'> ignored

### CODE REVIEW

**Comment by polaroi8d** [comment]
This is a valid solution? Did you tested?

**Comment by maxkrivich** [comment]
@polaroi8d yes

**Comment by shashrvacai** [comment]
I made the required changes but I still get the same error.. Im using mac.

**Comment by shashrvacai** [comment]
ALso I tried the repo  @ChipWolf 's account  ... i still get the same error ..

**Pull request merged**
