### PR TITLE
Fixing unfollow bug

### PR DESCRIPTION
**Pull request by andrewsegas**
user_info schema has been changed

### CODE REVIEW

**Comment by JoeFertig** [comment]
Hey @andrewsegas thanks for your work.
Somehow the unfollow is still not working. I did the changes in the instabot.py and tried it but it only unfollows if you stop the routine by ctrl+c.
Any suggestions?

**Comment by andrewsegas** [comment]
@JoeFertig send the error

**Comment by JoeFertig** [comment]
@andrewsegas 
Here is the Terminal output after successful login. After several unfollow attemps I interrupt the routine with ctrl+c at 15.03.2018_10:48. I did all changes in "userinfo.py", "user_info.py" and "instabot.py".

15.03.2018_10:39 Get media id by tag: tattoo
15.03.2018_10:39 Removing already liked medias..
15.03.2018_10:39 Trying to like media: 1735491893482434700
15.03.2018_10:39 Liked: 1735491893482434700. Like #1.
15.03.2018_10:39 Trying to follow: 1739814688
15.03.2018_10:39 Followed: 1739814688 #1.
15.03.2018_10:39 Trying to unfollow #1: 
15.03.2018_10:39 Getting user info : aguatape_ecotours
15.03.2018_10:39 Checking user info..
15.03.2018_10:43 Trying to like media: 1735491882627037185
15.03.2018_10:43 Liked: 1735491882627037185. Like #2.
15.03.2018_10:43 Trying to unfollow #1: 
15.03.2018_10:43 Getting user info : lagossnorkeling
15.03.2018_10:43 Checking user info..
15.03.2018_10:44 Trying to follow: 339149362
15.03.2018_10:44 Followed: 339149362 #2.
15.03.2018_10:46 Trying to like media: 1735491810929593913
15.03.2018_10:46 Liked: 1735491810929593913. Like #3.
15.03.2018_10:46 Get media id by tag: ocean
15.03.2018_10:46 Removing already liked medias..
15.03.2018_10:48 Trying to unfollow #1: 
15.03.2018_10:48 Getting user info : ez_inktattoos
15.03.2018_10:48 Checking user info..
15.03.2018_10:48 Trying to follow: 1793198227
15.03.2018_10:48 Followed: 1793198227 #3.
^CTraceback (most recent call last):
  File "Instabot/Wifey/example.py", line 76, in <module>
    bot.new_auto_mod()
  File "/home/pi/Instabot/Wifey/src/instabot.py", line 703, in new_auto_mod
    time.sleep(3)
KeyboardInterrupt
15.03.2018_10:50 Trying to unfollow: 1739814688
15.03.2018_10:50 Unfollow: 1739814688 #1 of 3.
15.03.2018_10:50 Pausing for 19 seconds... 1 of 3
15.03.2018_10:50 Trying to unfollow: 1793198227
15.03.2018_10:50 Unfollow: 1793198227 #2 of 3.
15.03.2018_10:50 Pausing for 23 seconds... 2 of 3
15.03.2018_10:50 Logout: likes - 3, follow - 3, unfollow - 2, comments - 0.
15.03.2018_10:50 Bot work time: 0:11:16.210306
15.03.2018_10:50 Logout success!

**Comment by RaymondLv** [comment]
it's doing a clean up. It's unfollowing only the accounts it followed. I have a similar problem

**Comment by andrewsegas** [comment]
@JoeFertig and @RaymondLv I didn't get what is going on.
the source code doesn't seem with error

Here it works https://github.com/andrewsegas/instaboost

**Comment by JoeFertig** [comment]
@andrewsegas running your instaboost results in an error too:

python instaboost.py
Traceback (most recent call last):
  File "instaboost.py", line 3, in <module>
    from PyQt5.QtWidgets import *
ImportError: No module named PyQt5.QtWidgets

**Comment by andrewsegas** [comment]
@JoeFertig 
pip3 install pyqt5

**Comment by JoeFertig** [comment]
@andrewsegas thanks! So this runs on python3? Not sure if I want to install it cause then no python2 code will work anymore right?

**Comment by andrewsegas** [comment]
@JoeFertig both will work, let's update our life

**Comment by andrewsegas** [comment]
@JoeFertig Now we already have example.py there, to run just in prompt without User Interface
This one you don't need to update to python3

**Comment by JoeFertig** [comment]
@andrewsegas thank you looks like it is working. Will do some more testing and come back to you :)

**Comment by williamwashere** [comment]
Hi @andrewsegas it's not working. The output shows that is "unfollowing" but in fact it doesn't.

**Comment by andrewsegas** [comment]
@williamwashere are you talking about which project? may you, please, open issue in instaboost (if you're talking about instaboost)?

**Comment by williamwashere** [comment]
The fix that you delivered is related to Instabot right? So I'm talking about Instabot. @andrewsegas

**Comment by andrewsegas** [comment]
@williamwashere No man, Here in instabot we always need to find which PR is right, they are not updating the project anymore.
here https://github.com/andrewsegas/instaboost the project is updated and everything is working, we have some differents features as well.

**Comment by coooling123** [comment]
@andrewsegas im about to test your code bro I've tested all of them and have gotten them to work, im going to test this one now let you know

**Comment by williamwashere** [comment]
@andrewsegas interesting, I didn't know they're not updating. Thank you.

**Comment by rinat-khantimirov** [comment]
change this in instabot.auto_unfollow()
between 848 - 856 lines

```
user_info = all_data['graphql']['user']
i = 0
log_string = "Checking user info.."
self.write_log(log_string)

follows = user_info['edge_follow']['count']
follower = user_info['edge_followed_by']['count']
media = user_info['edge_owner_to_timeline_media']['count']
```

**Comment by ChipWolf** [comment]
@andrewsegas you have not attempted to contact any of the maintainers directly. We'll issue a takedown on your repo if it isn't removed. Send me the PRs you'd like merged directly.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Pull request closed without merging**
