### PR TITLE
Update instabot.py

### LINKED ISSUE #1153: Json Decoder
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 

## Python Version?
3

## Description

Hi guys, I started to have this issue today, I've been using the bot for a couple of weeks and it has worked okay. I really don't understand the error log, at first I thought it has to be something about the packages or the version so I updated everything and it still hasn't worked.

```
Traceback (most recent call last):
  File "example.py", line 63, in <module>
    unfollow_whitelist=[])
  File "C:\Users\David Ramírez\Desktop\Python\instabot\instabot.py\instabot.py\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\David Ramírez\Desktop\Python\instabot\instabot.py\instabot.py\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\David Ramírez\Desktop\Python\instabot\instabot.py\instabot.py\src\userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\David Ramírez\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\David Ramírez\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\David Ramírez\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

### PR DESCRIPTION
**Pull request by Instaerror**
Fixes  #1153

### CODE REVIEW

**Comment by Instaerror** [comment]
No idea what you mean.

**Comment by Instaerror** [comment]
Fix it yourself then 👍

**Comment by joilson-cisne** [comment]
Why did you closed the PR @ghost? It worked for me. Thanks.

**Comment by nivong** [comment]
ghost is a "fake" account he deleted his account

**Pull request closed without merging**
