### PR TITLE
Fix for userinfo.get_user_id_by_login() (issue #1153)

### PR DESCRIPTION
**Pull request by elebertus**
- Still make the call through `userinfo.get_user_id_by_login()` but inspect the status code before trying to serialize the body.
- Return `None` type from function and handle `None` in `login()`
- Inspect the session cookie of the login session for the `ds_user_id` key and use it for the userid.

There might be cases where this doesn't work, if somehow cookies are not enabled for the session (other stuff would break) or the cookie schema changes. I would suggest removing the external call to retrieve the userid entirely  if the cookie method is functional.

### CODE REVIEW

**Comment by davidhearnsmith** [comment]
Instagram removed the json page yet the json is in the main page and freely available, this makes no sense.

**Comment by davidhearnsmith** [comment]
Also @instaerror fixed this days ago. Works perfectly throughout all modes. Yet nothing applied 👎

**Comment by elebertus** [comment]
@davidhearnsmith is there integration somewhere with whatever project you're talking about?

TBH I don't really mind if you guys want this code. I've been running it in my fork without issues. It's arguably as fragile as being reliant on the private api for responses.

**Comment by elebertus** [comment]
@davidhearnsmith can you link the code that you're talking about, or open a PR to merge it into the project?

**Pull request closed without merging**
