### PR TITLE
user input added

### PR DESCRIPTION
**Pull request by YannickLeRoux**
I thought it would be good not at have a password openly accessible on the computer but rather ask the user to actually login

### CODE REVIEW

**Comment by Alphavader** [comment]
This feature is interesting for running the Script from  a server.

**Comment by ChipWolf** [comment]
I like this addition.

**Comment by orensbruli** [comment]
@ChipWolf I think it resolves not to be worried all the time about uploading our username and password every time we make a push of the code. What do you think?

**Comment by ChipWolf** [comment]
There's a promising PR coming up @orensbruli

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Pull request closed without merging**
