### PR TITLE
logical conditions refactoring

### PR DESCRIPTION
**Pull request by nikolasvargas**

### CODE REVIEW

**Comment by yurilaaziz** [comment]
Thank you for your interest 
Could you please make the change refactoring for other code, please?

**Comment by nikolasvargas** [comment]
When I refactor it, do you mind if I split the code into different modules?

**Comment by yurilaaziz** [comment]
not at all,  go head 
But could you create an issue and explain your approach first. it's good to track changes with issues
There is a lot of duplicate code too if you can refine it.

**Comment by yurilaaziz** [comment]
rebased

**Pull request closed without merging**
