### PR TITLE
Refactored the Login function

### PR DESCRIPTION
**Pull request by DarkSuniuM**
Refactored some parts of login function, Handled wrong Username/Pw, Challenge required, Error from Instagram, Other status codes and successful login!
Still has the Challenge problem, Sometimes it works, Sometimes it doesn't

### CODE REVIEW

**Comment by Gx0st** [comment]
Hello DarkSuniuM, is the bot working again? I don't understand the pull requests section but it seems like you have fixed it? I would appreciate the response as I do want to use the program but have had problems with using it. It doesn't work and logs me out 2 seconds when I used the pull request from user LopesX. So I just change the files you've fixed and it will work?

**Comment by DarkSuniuM** [comment]
> Hello DarkSuniuM, is the bot working again? I don't understand the pull requests section but it seems like you have fixed it? I would appreciate the response as I do want to use the program but have had problems with using it. It doesn't work and logs me out 2 seconds when I used the pull request from user LopesX. So I just change the files you've fixed and it will work?

Use the main repository, it's working, yeah

**Comment by Gx0st** [comment]
> > Hello DarkSuniuM, is the bot working again? I don't understand the pull requests section but it seems like you have fixed it? I would appreciate the response as I do want to use the program but have had problems with using it. It doesn't work and logs me out 2 seconds when I used the pull request from user LopesX. So I just change the files you've fixed and it will work?
> 
> Use the main repository, it's working, yeah

Thank you for fixing it. I am running it and it is working. I wish I could donate to you. But no money right now. All I can say is thank you for your time and effort to helping each and every one of us succeed.

**Comment by Gx0st** [comment]
How do I add more than one account?

**Pull request merged**
