### PR TITLE
log_mod=2 added

### PR DESCRIPTION
**Pull request by linkfy**
When log_mod = 2
Generate txt file with the same name as file
Save only last few logs (~50)
Show log also in screen
Tested on Windows 10 and Mac OS X El Capitan with Python 2.7

### CODE REVIEW

**Comment by LevPasha** [comment]
Guys, need test it!

**Comment by Killerherts** [comment]
Windows 7 and Windows 10 tested no issues

**Comment by LevPasha** [comment]
@linkfy "This branch has conflicts that must be resolved"

**Comment by Killerherts** [comment]
Awe damn what did I miss

**Comment by Killerherts** [comment]
Nvm I didn't see u had another merg he just needs to update

**Comment by LevPasha** [comment]
@linkfy wait for update...

**Comment by linkfy** [comment]
@LevPasha ready :)

**Comment by Killerherts** [comment]
This is ready for a merge and is needed i use it all the time

**Comment by ChipWolf** [comment]
@linkfy refactor

**Comment by taradell** [comment]
hi guys! how can i help to fix mode 2?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Pull request closed without merging**
