### PR TITLE
Fix Login Issue

### PR DESCRIPTION
**Pull request by felangga**
Fix login issue 

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/osmc/pwn/bot/instabot.pyV2/src/instabot.py", line 227, in __init__
    self.login()
  File "/home/osmc/pwn/bot/instabot.pyV2/src/instabot.py", line 296, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/osmc/pwn/bot/instabot.pyV2/src/userinfo.py", line 45, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

### CODE REVIEW

**Comment by Hiwakea** [comment]
I have a similar KeyError Issue

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/dieopauel/Desktop/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/dieopauel/Desktop/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/dieopauel/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

What do I do? Thanks in Advance <3

**Comment by bhatmohsin1913** [comment]
same  issue plz help me ..bhatmohsin1913@gmail.com

**Comment by bhatmohsin1913** [comment]
thanks a lot..i will try to do it.

**Comment by bhatmohsin1913** [comment]
Can u please send me a screenshot where to change..i m not getting it
well...plzz...fast

**Comment by felangga** [comment]
Open file userinfo.py inside folder src
replace the red line with the green line
image

**Comment by bhatmohsin1913** [comment]
Thanku i will try this

**Comment by bhatmohsin1913** [comment]
Not working dear...It is showing the same issue again

**Comment by bhatmohsin1913** [comment]
Thanks a lot dear...It is done....U are great...Please add me on instagram
my username bhatmohsin1913

**Comment by Hiwakea** [comment]
Got it to work too! Thanks! Fantastic!

**Comment by Conorbro** [comment]
This has already been solved via #1055.

**Pull request closed without merging**
