### PR TITLE
Fix common login issue (Traceback Error)

### PR DESCRIPTION
**Pull request by cyborgafterall**
This is a simple and tested fix for Issue #1522.

### CODE REVIEW

**Comment by sweleck** [comment]
Works for me as well. Thanks.

**Comment by jilliankeenan** [comment]
Out of interest can you explain why this was the fix for the login issue I had? 

Simply for learning purposes.

Thanks!

**Comment by iamdatman** [comment]
Wow. It works like magic

**Comment by luxarts** [comment]
Good job!

**Comment by danilogit** [comment]
Why not grab only the graphql portion of JSON? Thus we can prevent errors in future changes.
Something like this?
```
        search = re.search('(\"graphql\".+is_business_account)', info.text, re.DOTALL)
        json_info = json.loads('{' + search.group(0) + '":false }}}')
        id_user = json_info['graphql']['user']['id']
```

**Comment by trrinsta** [comment]
I'm kinda new to this program and have no idea what to do. I keep getting a 
Login error! Connection error!
 Removing already liked medias..
I know my login info is correct but it won't let me login

**Pull request closed without merging**
