### PR TITLE
Fixing json parsing in userinfo.py

### PR DESCRIPTION
**Pull request by renatojen**
This fixes the error:

json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
#1718

### CODE REVIEW

**Comment by neozonx123** [comment]
after replacing the new code, the error is still there :(

**Comment by renatojen** [comment]
> after replacing the new code, the error is still there :(

Did you try in a clean instabot-py copy? I'm getting replies from many people saying it's working.
Just tested right now and it is working just fine.

**Comment by JerryWNYC** [comment]
Seems I'm having the same issue.  I'm new to python so forgive any ignorance.
When running the bot (renamed benbot) I get the responses below.  
The final error is the one related to "userinfo.py, line 42".
I suspect the earlier ones are also caused by the same error but am not sure about this.
Please help.  
Thanks.

Traceback (most recent call last):
  File "benbot.py", line 52, in <module>
    unfollow_whitelist=[''])
  File "C:\Users\Infostar\Desktop\BOT\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\Infostar\Desktop\BOT\instabot.py-master\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Infostar\Desktop\BOT\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Gabro89r** [comment]
If I try to fix it i've got this error now:
Traceback (most recent call last):
  File "/XXX/XXX/XX/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/XXX/XXX/XX/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/XXX/XXX/XX/instabot.py-master/src/instabot.py", line 289, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/XXX/XXX/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/XXX/XXX/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by marcocario** [comment]
Please, follow my instruction https://github.com/instabot-py/instabot.py/issues/1509#issuecomment-437551513

**Comment by enrifer** [comment]
I made a clean install. Still get those errors: Maybe someone can help. Thanks a lot 👍 

Traceback (most recent call last):
  File "c:/Users/danie/Desktop/Insta/instabot.py-master/example.py", line 6, in <module>
    from src import InstaBot
  File "c:\Users\danie\Desktop\Insta\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "c:\Users\danie\Desktop\Insta\instabot.py-master\src\instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "c:\Users\danie\Desktop\Insta\instabot.py-master\src\userinfo.py", line 42
    json_info = json.loads(re.search('window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))
    ^
IndentationError: unexpected indent

**Comment by marcocario** [comment]
> I made a clean install and changed line 42. Still get those errors: Maybe someone can help. Thanks a lot 
> 
> Traceback (most recent call last):
> File "c:/Users/danie/Desktop/Insta/instabot.py-master/example.py", line 6, in 
> from src import InstaBot
> File "c:\Users\danie\Desktop\Insta\instabot.py-master\src__init__.py", line 1, in 
> from .instabot import InstaBot
> File "c:\Users\danie\Desktop\Insta\instabot.py-master\src\instabot.py", line 6, in 
> from .userinfo import UserInfo
> File "c:\Users\danie\Desktop\Insta\instabot.py-master\src\userinfo.py", line 42
> json_info = json.loads(re.search('window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))
> ^
> IndentationError: unexpected indent

@enrifer https://github.com/instabot-py/instabot.py/issues/1509#issuecomment-437551513 please check my comment

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/pull/1732

Dont want to change requirements.txt so

**Comment by italiana77** [comment]
@marcocario ho sistemato l'userinfo.py come hai suggerito ma ora mi compare quest'altro problema:


MacBook-Pro:instabot.py-master Fabiana$ python3 example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/Fabiana/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/Fabiana/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import userInfo
  File "/Users/Fabiana/Desktop/instabot.py-master/src/userinfo.py", line 3
    -- coding: utf-8 --
                      ^
SyntaxError: invalid syntax



PS: non riesco a capire questa parte che mi hai scritto….saresti così gentile da spiegarmi? (non sono pratica)

example

ui = UserInfo()

search by user_name:

ui.search_user(user_name="danbilzerian")

or if you know user_id ui.search_user(user_id="50417061")

print(ui.user_name)
print(ui.user_id)

get following list with no limit

ui.get_following()
print(ui.following)

get followers list with limit 10


Grazie mille

**Comment by marcocario** [comment]
Ciao, penso che l'errore sia dovuto ad un copia incolla fatto male. Passami
un email cosi ti invio il file direttamente.

Marco

Il giorno mar 20 nov 2018 alle ore 13:12 italiana77 <
notifications@github.com> ha scritto:

**Comment by italiana77** [comment]
@marcocario mrs78@msn.com

**Pull request closed without merging**
