### PR TITLE
A lot of commits and features

### PR DESCRIPTION
**Pull request by ugurozturk**
I think it would be better if you create a new branch called v1.2 so we can keep this branch as it is now. And let the community test the repo. I dont trust the git that much and there is 18 files changed,  with 521 additions and 254 deletions. 

If you trust git that much and you say that we can fix if there would be a problem then merge it. My code is working

### CODE REVIEW

**Comment by ugurozturk** [comment]
if anybody wonder the changes summary.

1. liked medias saving to sqlite3
2. followed usernames saving to sqlite3
3. Doesn't try to like again and time saving.
4. Doesn't follow a person again. (To avoid spamming and getting reported)
5. changed ig_ numbers.
6. Start and stop time.

**Comment by ugurozturk** [comment]
@ChipWolf So yeah i made the PR and send you an mail to the details of what i am going to make when i became a Collaborator

**Comment by ChipWolf** [comment]
squash your commits please.

**Comment by ugurozturk** [comment]
@ChipWolf there is one thing i didn't delete, https://github.com/instabot-py/instabot.py/pull/884/files#diff-91adcadbdf4fad3eb76d66f30bfba3afR363 ` """ Get Media Code or Full Url from Media ID Thanks to Nikished """` it is not mine functions so i made this comments to ping him. If you think it also must be deleted tell me.

Also i think it is oke now. What you think ?

**Comment by ugurozturk** [comment]
@ChipWolf perhaps you saying should i make like 1 commit for all ?

**Comment by ChipWolf** [comment]
I mean.. that works I guess. Maybe not quite so dramatic.
Like.. a feature or fix per commit would be nice for readibility
Loads of commits like 'changed some', 'fixed this', 'updated' are not very useful to anyone.

**Comment by ChipWolf** [comment]
https://github.com/troessner/articles/blob/master/2014-12-20-why-you-should-squash-your-commits.markdown

**Comment by ugurozturk** [comment]
Merged via https://github.com/instabot-py/instabot.py/commit/f0431d42d161f5663195bc3c2a54aea8dc0d6788

**Pull request closed without merging**
