### PR TITLE
Keep a database with followers (no duplicated followers this way)

### PR DESCRIPTION
**Pull request by nivong**
Hey guys, like many of you I got complaints of the bot refollowing people and that not only is an obvious sign of bot activity, it also waists a follow opportunity. I had the code adjusted to write a db file of people it followed and not follow them again. 
This new code will also allow capitals in the comments instead of undercasing them just don't forget to add your comments back in the file if you want to.

### CODE REVIEW

**Comment by LevPasha** [comment]
@nivong do you test it on windows?

**Comment by nivong** [comment]
I don't have windows only Linux. And I'm still testing this so please don't sync yet.

**Comment by Plushkin** [comment]
good job, it's can be merged?

**Comment by ratacat** [comment]
@nivong Just an additional possible use-case...I want to run this bot on an existing instagram account without messing up the feed!! So I want to be super careful to unfollow all of the bot created follows, and no others.  Seems like the database would be a prime way to do that. But I'm thinking maybe thats not quite how you have it hooked up right now.  For the moment, I'm trying to use unfollow_whitelist, however I haven't been able to extract the list of all the people the account is currently following. The UserInfo calls have definitely not been working for me.  Any suggestions or ideas?

**Comment by LevPasha** [comment]
@nivong write when you ready

**Comment by nicholaai** [comment]
Would love to have this feature, looking forward to the merge!

**Comment by nivong** [comment]
I haven't had a change to write this too much going on atm in my life ;)

**Comment by ChipWolf** [comment]
Refactor.

**Comment by nivong** [comment]
closing thakns @ChipWolf

**Comment by ChipWolf** [comment]
I'm opening this again because I'd like to see a database solution. We will probably have to start a new branch/PR to work on this, it'll be a major change.

**Comment by MrHakala** [comment]
I'd like to see this as well. Following the same people repeatedly is a real problem. Also this setup could open up instabot "tag teams". ie. bots working together on same keywords without double follows.

**Comment by nivong** [comment]
ill see what I can do to make this usable.

**Comment by ChipWolf** [comment]
@MrHakala I propose a `hive_mind` function, add slave bots to an Instabot cluster.
The evil Instagram takeover plans are slowly coming into effect.

**Comment by nicholaai** [comment]
review? @ChipWolf

**Comment by ChipWolf** [comment]
@nivong could you squash a few of these commits with duplicate names?

**Comment by Josh452** [comment]
@nivong You should problem also should have said that you removed the text comments and replaced them with emoji comments 👍  But can't wait for this to be added.

**Comment by nivong** [comment]
@ChipWolf i really dont have the time, this weekend I might have a little time to check it out, it has been a while since I was going through coding (my dayjob is totally different to coding lol)

**Comment by twont** [comment]
I have done this the 'lazy' way - with a simple read/write - but have chose to store the post / user IDs as plain text, so that they can be read by a human

**Comment by ChipWolf** [comment]
@twont could you PR that on a different branch?

**Comment by frax20** [comment]
Hi! @twont I did all you said in your post but It continuing to follow the same person..
Seems to me (even if i'm not a programmer) that It is not able to get different id from an hashtag but it just take the first he get.. Could it be?
Thank you

**Comment by ChipWolf** [comment]
@frax20 I'm actually testing @twont's implementation right now; seems to be doing exactly as intended

**Comment by ChipWolf** [comment]
@twont 


looks like your method is duplicating followers

**Comment by ChipWolf** [comment]
@nivong progress check

**Comment by ChipWolf** [comment]
@twont paging

**Comment by nivong** [comment]
I must admit I am not using the bot anymore nor developing for at this current time sorry. Have other priorities during summer :)

**Comment by ChipWolf** [comment]
Will reallocate

**Comment by nivong** [comment]
let me try and tidy it a up bit for ease of use

**Comment by ChipWolf** [comment]
@nivong appreciated, if necessary we can fork and continue

**Comment by nivong** [comment]
closing this and opening a new PR.

**Pull request closed without merging**
