### PR TITLE
Add follow_user_follower mode 

### PR DESCRIPTION
**Pull request by awesome205**
Hi, 

I am not sure how to add a follow_user_follower mode and have tried numerous way but have been unsuccessful.

Instead of follow_per_day from hashtags would it be possible to create a function that would do follow_per_day using a user's followers?

Thanks.

### CODE REVIEW

**Comment by Raziel15** [comment]
Yes please I would like that too !

**Comment by butaminas** [comment]
This is a much needed feature.

**Comment by marcopalla** [comment]
Every online service  follow/unfollow arount 10$ a month  offers this kind of function.
Is a must. Follow on last post on ashtags not work
We need to follow a specific target, the followers of an account.
goood work my friends .

**Comment by oakleyblack** [comment]
I had a 3 day trial of a service called "SocialDrift" and they had this feature! it seemed to have the best results. I've been looking for this feature on this bot for the past few days and cannot find anything. please add this!

**Comment by Emahhh** [comment]
Yes, I was asking for the same thing!
I hope that the developer will add this feature soon. 
(Or maybe someone could fork this project)

**Comment by collaxd** [comment]
Yes! please Like and interact on last post on x page likers, etc, awesome!

**Comment by ShakreeElmi** [comment]
Error:

03.07.2018_18:51 Trying to login as zulariffinfamilia...

Traceback (most recent call last):
  File "c:/Users/shakreeelmi/Desktop/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "c:\Users\shakreeelmi\Desktop\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "c:\Users\shakreeelmi\Desktop\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "c:\Users\shakreeelmi\Desktop\instabot.py-master\src\userinfo.py", line 43, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\shakreeelmi\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\shakreeelmi\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\shakreeelmi\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by freaky1** [comment]
How do you add the Instagram acccount you want the bot to take followers from? I can't find anywhere in Instabot.py where i can add the name?

**Comment by Nikaze** [comment]
I would love to use this feature too. Is it possible?

**Comment by thibob38** [comment]
Is it possible ? would be amazing!

**Comment by Nikaze** [comment]
@ugurozturk where do we type in the user's info so that we can interact with the user's followers?

**Comment by DuskeZ** [comment]
@ugurozturk So where do we put user’s info which we are targeting?

**Pull request closed without merging**
