### PR TITLE
fix for comments

### PR DESCRIPTION
**Pull request by raymondma1**
this PR should address the issue in #522. The 'media' key in all_data no longer exists and the underlying key values have also changed because of the graphql api update.

### CODE REVIEW

**Comment by hoseinit** [comment]
hope to overcome the problem

**Comment by EmbeddedAndroid** [comment]
Traceback (most recent call last):
  File "/instabot.py/nwdrone.py", line 59, in <module>
    bot.new_auto_mod()
  File "/instabot.py/src/instabot.py", line 564, in new_auto_mod
    self.new_auto_mod_comments()
  File "/instabot.py/src/instabot.py", line 619, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/instabot.py/src/instabot.py", line 646, in check_exisiting_comment
    all_data_media = all_data['graphql']['shortcode_media']
NameError: global name 'all_data' is not defined

**Comment by EmbeddedAndroid** [comment]
@raymondma1 this fixes the stacktrace for me: https://github.com/EmbeddedAndroid/instabot.py/commit/98b97ddbd7e52622e1572b6a3e01dc703066b13b

**Comment by EmbeddedAndroid** [comment]
LGTM, thanks!

**Comment by Josh452** [comment]
This can be closed @raymondma1. A fix for it has already been merged.

**Pull request closed without merging**
