### PR TITLE
Unlike likes after x time

### PR DESCRIPTION
**Pull request by ThomasTJdev**
## Issue
Your profile history is getting spammed up by strange likes.

## Solution
Start unliking after a specified time interval.
When you have liked more than 1 post (2 likes) AND your delay time (unlike_like_after) has finished, you'll start unliking a post in the same interval, as you'll like them.

## How to
Specify the parameter unlike_like_after in seconds in example.py
`unlike_like_after=3600` = Waits approximate 3600 seconds
`unlike_like_after=0` = Disabled

## Changes
Unlike function is modified: `unlike(self, media_id)`
New iteration function created: `new_auto_mod_unlike(self)`
New unlike cleanup function created: `unlike_on_cleanup(self, media_id)`
self.like_status to control that a like has worked
Minor changes

## Issues/todo
Instead of dealy timer, just use a simple "unlike after x likes" with `self.like_counter`

### CODE REVIEW

**Comment by LevPasha** [comment]
Test this too! TXH!

**Comment by ThomasTJdev** [comment]
@LevPasha, I've been doing a long test run, and I think the pull might has a problem with counting the number of unlikes (or likes?). While doing the the cleanup, the self.unlike_counter can get higher than the self.like_counter. I can't seem to find where the counting is going wrong.

**The mod_unlike should only run if like_status is equal to 1.**
```python
def new_auto_mod_unlike(self):
    if self.unlike_like_after != 0 and self.like_status == 1:
```

**The like_status should change to '1' after a successful like (`like(self, media_id)`):**
```python
    try:
        like = self.s.post(url_likes)
        last_liked_media_id = media_id
        self.media_liked_by_id += [media_id]
        self.like_status = 1
    except:
        self.write_log("Except on like!")
        self.like_status = 0
```

**The unlike counter should only increase, if an unlike is successful (`def unlike(self, media_id)`):**
```python
try:
    unlike = self.s.post(url_unlike)
    self.unlike_counter += 1
```

**The unlike counter should only increase, if status_code == 200 in the cleanup (`unlike_on_cleanup(self, media_id)`):**
```python
if unlike.status_code == 200:
    self.unlike_counter += 1
```

**Comment by polaroi8d** [comment]
Rebase the PR, there is a conflict.

**Comment by ChipWolf** [comment]
Pretty tame conflict @polaroi8d, test please

**Comment by ChipWolf** [comment]
Refactor.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Pull request closed without merging**
