### PR TITLE
fixed KeyError 'likes' issue

### PR DESCRIPTION
**Pull request by aferook**
Error appears in mode=2 and mode=5 (which is using mode=2)

### CODE REVIEW

**Comment by andrste** [comment]
@aferook I think this is not working correctly. Take a look! And it goes in cycle ...

```
============================== 
Upss hajka is already in ex user list... 
==============================
10.06.2018_10:43 ig_username : Get media id on recent feed 
 10.06.2018 10:43
10.06.2018_10:43 Except on get media!!
10.06.2018_10:43 ======> Get media id by Tag <======
10.06.2018_10:43 Get media by user success!
============================== 
Upss hajka is already in ex user list... 
==============================
10.06.2018_10:43 ig_username : Get media id on recent feed 
 10.06.2018 10:43
10.06.2018_10:43 Except on get media!!
10.06.2018_10:43 ======> Get media id by Tag <======
10.06.2018_10:44 Get media by user success!
============================== 
Upss hajka is already in ex user list... 
==============================
10.06.2018_10:44 ig_username : Get media id on recent feed 
 10.06.2018 10:44
10.06.2018_10:44 Except on get media!!
10.06.2018_10:44 ======> Get media id by Tag <======
10.06.2018_10:44 Get media by user success!
============================== 
```

**Comment by SujalKokh** [comment]
I think this is still not working correctly. I m getting a repeat output. The output exactly same as @andrste

**Comment by ChetansHyper** [comment]
yeah the same issue "Upss hajka is already in ex user list..."

**Comment by kostasosfp** [comment]
finally will these chages solve this problem?

**Comment by kostasosfp** [comment]
**SAME PROBLEM AS ABOVE ... THIS CHANGE DOESN'T FIX THE PROBLEM!**

17.10.2018_11:56 Trying to login as e@@@@y...

17.10.2018_11:56 e@@@@y login success!
17.10.2018_11:56 Get Media by tag: greece
17.10.2018_11:56 Removing already liked medias..
17.10.2018_11:56 Trying to like media: 1892021622821270930
17.10.2018_11:56 Liked: 1892021622821270930. Like #1.
17.10.2018_11:56 Trying to follow: 3602002888
17.10.2018_11:56 Followed: 3602002888 #1.
17.10.2018_11:56 e@@@@y : Get media id on recent feed
 17.10.2018 11:56
17.10.2018_11:56 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
17.10.2018_11:56 e@@@@y : Get media id on recent feed
 17.10.2018 11:56
17.10.2018_11:57 Except on get media!!
17.10.2018_11:57 ======> Get media id by Tag <======
17.10.2018_11:57 Get media by user success!
17.10.2018_11:57 Current Index = 38 of 71 medias
17.10.2018_11:57 Current Index = 35 of 70 medias
17.10.2018_11:58 Current Index = 11 of 69 medias
17.10.2018_11:58 Current Index = 56 of 68 medias
17.10.2018_11:59 e@@@@y : Get media id on recent feed
 17.10.2018 11:59
17.10.2018_11:59 Except on get media!!
17.10.2018_11:59 ======> Get media id by Tag <======
17.10.2018_11:59 Get media by user success!
==============================
Upss hajka is already in ex user list...
==============================
17.10.2018_12:00 e@@@@y : Get media id on recent feed
 17.10.2018 12:00
17.10.2018_12:00 Except on get media!!
17.10.2018_12:00 ======> Get media id by Tag <======
17.10.2018_12:00 Get media by user success!
==============================
Upss hajka is already in ex user list...
==============================
17.10.2018_12:00 e@@@@y : Get media id on recent feed
 17.10.2018 12:00
17.10.2018_12:00 Except on get media!!
17.10.2018_12:01 ======> Get media id by Tag <======
17.10.2018_12:01 Get media by user success!
==============================
Upss hajka is already in ex user list...
==============================
17.10.2018_12:01 e@@@@y : Get media id on recent feed
 17.10.2018 12:01
17.10.2018_12:01 Except on get media!!
17.10.2018_12:01 ======> Get media id by Tag <======
17.10.2018_12:01 Get media by user success!
==============================
Upss hajka is already in ex user list...
==============================
17.10.2018_12:02 e@@@@y : Get media id on recent feed
 17.10.2018 12:02
17.10.2018_12:02 Except on get media!!
17.10.2018_12:02 ======> Get media id by Tag <======
17.10.2018_12:02 Get media by user success!
==============================
Upss hajka is already in ex user list...
==============================
17.10.2018_12:02 e@@@@y : Get media id on recent feed
 17.10.2018 12:02
17.10.2018_12:02 Except on get media!!
17.10.2018_12:03 ======> Get media id by Tag <======
17.10.2018_12:03 Get media by user success!
==============================
Upss hajka is already in ex user list...
==============================
17.10.2018_12:03 e@@@@y : Get media id on recent feed
 17.10.2018 12:03
17.10.2018_12:03 Except on get media!!

**Comment by yakuzy** [comment]
I just had the same issue and found a solution!! https://github.com/instabot-py/instabot.py/blob/191c960aa78068a96d64e4ac0f9948e73bbd72d4/src/likers_protocol.py
Just replace your likers_protocol.py with this one

**Pull request closed without merging**
