### PR TITLE
Added support for location tags and added regex parsing for CSRF tokens

### PR DESCRIPTION
**Pull request by MarcoKCodes**
Added location support for tag_list by prefixing tags with l: as requested in #811 
Also added regex parsing for CSRF Token (was apparently previously submitted as PR in #1292)

### CODE REVIEW

**Comment by Martypary** [comment]
now my bot does nothing
I had first this error: KeyError: "name='csrftoken', domain=None, path=None"
can someone help me ?
( I have windows )

**Comment by MarcoKCodes** [comment]
@Martypary could you please check if your login credentials are right.

If not please open an issue in this repository.
Take the file [ISSUE_TEMPLATE.md](https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md) as template for your issue :)

**Comment by kajuken** [comment]
@MarcoKCodes well done!

Is it also possible to let the program like provided hashtags within a certain location. So we can make use of your added feature with the current state at the same time?

Example i provide a hashtag "#jobs" and a location "l:123456789" and it will only follow/like posts having jobs as hashtag and being posted in this location.

Looking forward to your answer! :)

**Comment by MarcoKCodes** [comment]
@kajuken Currently that is sadly not possible with my implementation as it is only looking at https://www.instagram.com/explore/locations/%s/?__a=1 and afaik there is currently no way to combine this with a normal hashtag.

I am currently working on a solution for this though :)

**Comment by kajuken** [comment]
Thank you for the quick response!

Looking forward to your solution :)

**Comment by itkos** [comment]
@MarcoKCodes 
Good afternoon! Prompt function that the bot likal only on locations, without hashtavov. It's real? I can not do this .... I'm not very much in python. Please, help!

**Comment by ugurozturk** [comment]
@MarcoKCodes squash your commits please

i liked your location feature, yet i can't accept csrf_token regex. So can you make new PR for just location feature ?

**Comment by MarcoKCodes** [comment]
@ugurozturk created new PR #1414

**Comment by ugurozturk** [comment]
@ManicMartin i already fixed it, after merging his commit

**Pull request closed without merging**
