### PR TITLE
restructure for packaging and attach setup.py

### PR DESCRIPTION
**Pull request by yurilaaziz**
By applying this PR, this project will be PyPi Wheel compliant. it can be install by typing
`pip install instabot-py`
requirements will be fetched by pip directly instead of installing it by hand 
I already pushed version 0.2 of this package and marked it as Stable.

this project still need another refactor : 
- Replace all ugly prints with Logging module 
- Wrap all functions to related classes 
- Support Python 3.4 minimum 

Don't hesitate to add me to maintainers, I do python everyday 

Note: to new maintainers : I am glad to see you around this project again.

### CODE REVIEW

**Comment by dimisdas** [comment]
> Support Python 3.4 minimum

Instaloader requires Python >= 3.5. 
And since most popular OS repos should now have support for 3.6+, we opted for using f-strings, which are introduced in Python 3.6.

**Comment by yurilaaziz** [comment]
@dimisdas any update ?

**Comment by dimisdas** [comment]
@yurilaaziz should be fine/approved. Been working on it under branch pr/1930, will push my local tree soon.

 I think last thing on the list is Travis and then we merge.

**Comment by yurilaaziz** [comment]
I prefer doing a different PR for Travis, As actually there is no py tests.
I need also access to the organisation to link travis to it.
some tests need a dump account to run tests against  like authentication, comment, like , follow random account ...  

small changes are better than big one.

this pr is now stale need to be fixed.

**Comment by maxatbrs** [comment]
hey @yurilaaziz @dimisdas any update here? I like how we are placing everything in the `instabot` module in this PR, seems like a solid way of organizing the code.

If you want me to take a stab at the merge conflicts, lmk.

**Comment by yurilaaziz** [comment]
@dimisdas with travis 
added tox to manage py3.6 3.7

**Pull request merged**
