### PR TITLE
Login fix. Csrftoken fix. Unfollow method fix. Reset Token Method.

### PR DESCRIPTION
**Pull request by edmundpf**
Addresses Instagram JSON change. Login fixed. Fetches Csrftoken. Unfollow method implemented with new JSON structure. In case of 403 error due to csrftoken fetching error, will reset the token, eliminating the 403 errors. Tested and working.

### CODE REVIEW

**Comment by roviraleix** [comment]
for me it worked for 1 hour, after csrftoken again.. :(

**Comment by edmundpf** [comment]
@roviraleix could you send what errors you got? May have to wrap the reset_token method in a try statement upon failure. Also I had a typo in unfollow method I need to change. Will update soon

**Comment by rmaranhao** [comment]
Line 42 of src/userinfo.py shoud be
json_info = json.loads(re.search('{"activity.+gatekeepers', info.text, re.DOTALL).group(0)+'":""}')

**Comment by edmundpf** [comment]
@rmaranhao that's strange, if you look at the commits here it says I deleted that old line and added the new correct line.

**Comment by b4ckbre4ker** [comment]
@edmundpf error 400 is ip right? hehe i should of proxied first. :D oh well now using cyberghost and is working again.

**Comment by edmundpf** [comment]
@b4ckbre4ker yessir

**Comment by rmaranhao** [comment]
@edmundpf I viewed the raw file and copied/pasted it. All is fine.

@b4ckbre4ker could you point me to a solution using cyberghost? Can you get the bou to run on Google servers using cyberghost?

**Comment by edmundpf** [comment]
@rmaranhao not familiar with cyberghost just did a quick search and looks like a VPN, sorry I haven't tried with VPN, I'm guessing you would just set your server to run under your VPN IP and then run the bot and all should be well, its possible insta will notice this as a VPN though and give you 400 errors but that's unavoidable really, following and unfollowing still work in that case

**Comment by b4ckbre4ker** [comment]
@edmundpf it's actually a pretty amazing software, you can choose which country and where you want to have your VPN located.  I am paying monthly just trying it out $11 is worth it when i got 2 computers running multiple bots right now.  i can change ip address soon as one gets banned.

**Comment by b4ckbre4ker** [comment]
@rmaranhao - first ya gotta get rid of the 403 error.   I pasted the user_info and instabot.py codes on thread here

https://github.com/instabot-py/instabot.py/issues/1499

**Comment by variamus** [comment]
Hello, I tried to apply the fix but I'm getting troubles with unfollow:

> Getting user info : xxxxx
Trying to like media: xxxxx
Liked: xxxxx. Like #558.
Trying to like media: xxxxx
Liked: xxxxx. Like #559.
Trying to follow: xxxxx
Followed: xxxxx #392.
Trying to unfollow #1:
Getting user info : xxxxx
Trying to like media: xxxxx
Liked: xxxxx. Like #560.
Trying to like media: xxxxx
Liked: xxxxx. Like #561.
Trying to follow: xxxxx
Followed: xxxxx #393.
Trying to unfollow #1:
Getting user info : xxxxx
Trying to like media: xxxxx
Liked: xxxxx. Like #562.

As you can see, it's stuck. Can you help me ?

**Comment by 1achy** [comment]
i applied it is work

**Comment by adrianrossi46** [comment]
I copied the whole file DF74CAE, put my user and pass and get this error:
File "example.py", line 5, in <module>
    from .unfollow_protocol import unfollow_protocol
ModuleNotFoundError: No module named '__main__.unfollow_protocol'; '__main__' is not a package

**Comment by lucaasleaal** [comment]
Is stops after first like =\

**Pull request closed without merging**
