### PR TITLE
mode 1 base tested revision

### PR DESCRIPTION
**Pull request by ugurozturk**
feed scanner, follow protocol, post_page, user_feed, username_checker

### CODE REVIEW

**Comment by ugurozturk** [comment]
@ChipWolf So what do you think ?

**Comment by ChipWolf** [comment]
@ugurozturk reviewing

**Comment by ChipWolf** [comment]
:+1: RTM

**Comment by ugurozturk** [comment]
My code via mode 0 runs for hours now. And the changes also makes the works on mode=1 https://github.com/instabot-py/instabot.py/issues/899 . i dont know much about other modes

**Pull request merged**
