### PR TITLE
Fix user info schema

### PR DESCRIPTION
**Pull request by marcguilera**
For #1027

### CODE REVIEW

**Comment by tiagofabrica** [comment]
it worked, thanks

**Comment by williamwashere** [comment]
worked flawlessly, thank you @marcguilera for such fast fix.

**Comment by dipumahbub** [comment]
# **working but there's no user info, follower count, normal or not etc .** 
`14.03.2018_23:56 Getting user info : improveyourbodytr
14.03.2018_23:57 Trying to like media: 1735015157882726867
14.03.2018_23:57 Liked: 1735015157882726867. Like #2.
15.03.2018_00:00 Trying to like media: 1735016427615970415
15.03.2018_00:00 Liked: 1735016427615970415. Like #3.
15.03.2018_00:01 Trying to unfollow #1: 
15.03.2018_00:01 Getting user info : streetworkout_skills
15.03.2018_00:01 Trying to follow: 1823091395
15.03.2018_00:01 Followed: 1823091395 #2.
15.03.2018_00:02 Trying to like media: 1735015251650497415
15.03.2018_00:02 Liked: 1735015251650497415. Like #4.
15.03.2018_00:03 Trying to like media: 1735014091372921228
15.03.2018_00:03 Liked: 1735014091372921228. Like #5.
15.03.2018_00:05 Trying to like media: 1735016867348478643
15.03.2018_00:05 Liked: 1735016867348478643. Like # #6.`

**Comment by williamwashere** [comment]
@dipumahbub  that's true. Also I noticed that it's not unfollowing users.
@marcguilera it is expected?

**Comment by manguszta** [comment]
Yes, it fails to unfollow users.
```
Trying to unfollow #1:
Except on get info of [user]
```

**Comment by kwinrowjr** [comment]
i confirm, does not unfollow users

**Comment by marcguilera** [comment]
I had to change some more files for that. I looked at it yesterday and I have it "working" on my machine. It's really the first time I do python so I was jut trying to get it running, not sure about good practices and stuff.

**Comment by JordyVP** [comment]
Oh damn, totally missed that! Thanks!

**Comment by RaymondLv** [comment]
How to unfollow people who are not in the follow_db (not followed by the bot) with, for example, bot mode 5?

**Comment by jasperwonka** [comment]
Line 33 should be:
 media = user_info['graphql']['user']['edge_owner_to_timeline_media']['count']

**Comment by instabot-master** [comment]
you are amazing. that worked. thanks!

**Comment by Mr-nuke** [comment]
thank you works perfect

**Comment by lilrom13** [comment]
I implemented your changes but I'm still getting connection error. I'm using the bot on a vps.

**Comment by gersanchez** [comment]
Thanks!!! works Great!

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Pull request closed without merging**
