### PR TITLE
Posix color coding, tab indents, issue 295 failing safely, minor corr…

### PR DESCRIPTION
**Pull request by DrCherry**
…ections, and a user whitelist.  If environment is posix compliant, there is the start of color coding in the output. 

The rebase was too complicated for my small brain so I deleted my fork and re-created it.  I hope these changes serve the users.

### CODE REVIEW

**Comment by DrCherry** [comment]
@polaroi8d @LevPasha How does this one look?

**Comment by davisonio** [comment]
Awesome!

**Comment by LevPasha** [comment]
@DrCherry look good. Now instabot look like trash... But you test all of your work? I can't test it myself now.

**Comment by DrCherry** [comment]
Okay, I tested all the modes 1-5.  5 is now a test mode, but I just sketched it in.  I'd like someone else to try the modes before we merge, this is a LOT of changes.

**Comment by davisonio** [comment]
> Now instabot look like trash...

Yeah Instabot is really messy now...

**Comment by bobduckling221** [comment]
\Desktop\instabot.py-master\src\instabot.py", line 150, in init
    self.FAIL, self.ENDC, self.BOLD, self.UNDERLINE  = ''
ValueError: need more than 0 values to unpack


-Little error

**Comment by LevPasha** [comment]
@DrCherry Ok. I think i can try to merge? Let's do it today!
What about @bobduckling221 error?

**Comment by ChipWolf** [comment]
Lots of these issues have been solved. If you believe this is still a concern, clone a fresh copy of the repo, test, review the other PRs and make another if you feel it is necessary. Thanks.

**Pull request closed without merging**
