### PR TITLE
Dockerized and added a just like mode

### PR DESCRIPTION
**Pull request by bgokden**

### CODE REVIEW

**Comment by ChipWolf** [comment]
What's with the `app.py`? Let's not duplicate scripts, just use `example.py`

**Comment by bgokden** [comment]
@ChipWolf app.py takes variables from the environment since in docker usually configurations are passed as environment variables. 
I wanted to keep example.py as an example for people who don't use docker.

**Comment by ChipWolf** [comment]
Yeah, my concern is; the Docker assets are going to add further confusion for people who don't use Docker.

**Comment by TheBoroer** [comment]
Good stuff @bgokden !
+1 for a dockerized branch (it can autobuild on docker hub). I don't like messing around with my dev environment on my laptop, docker FTW!

**Comment by ChipWolf** [comment]
Make it happen!

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Pull request closed without merging**
