### PR TITLE
csrftoken fix

### PR DESCRIPTION
**Pull request by ivanchalov**
Fix recent issue with csrftoken

### CODE REVIEW

**Comment by bahadirtortop** [comment]
It worked for me.

file instabot.py line 287 replace with
csrf_token = re.search('(?<=\"csrf_token\":\")\w+',  r.text).group(0)
self.s.headers.update({'X-CSRFToken': csrf_token})
time.sleep(5 * random.random())

Ivan Chalov <notifications@github.com>, 6 Ara 2018 Per, 02:42 tarihinde
şunu yazdı:

**Comment by notmanhpham** [comment]
Able to login with this change but then I get "Not Liked: 403" almost immediately after login

**Comment by nachovoss** [comment]
> Able to login with this change but then I get "Not Liked: 403" almost immediately after login

install instaloader with pip first
then change code in instabot.py:
in my case:
line 18: import instaloader
line:162: self.instaload = instaloader.Instaloader()
and then in line 462 replace
 def get_username_by_user_id(self, user_id):
    if self.login_status:
        profile = instaloader.Profile.from_id(self.instaload.context,  user_id)
        username = profile.username
        return username
    else:
        return False
hope it helps

**Comment by niderhoff** [comment]
can confirm, this fixed it.

**Comment by manguszta** [comment]
This is a solution for 3 of my accounts, but not the 4th. Same CSRFToken KeyError... Tried to change password, tried to cool down for 48 hours, I can't make it work.

**Comment by rkovachev88** [comment]
I have this error now:

> raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
> KeyError: "name='csrftoken', domain=None, path=None"

**Comment by chris0211** [comment]
I've got the same Problem. but the solution is not working für me. :-( Any ideas?

**Comment by Eggwise** [comment]
Nice one.


Get this merged!

**Comment by dimisdas** [comment]
The changes have been implemented in different pull request and merged. Thanks everyone!

**Pull request closed without merging**
