### PR TITLE
Block Users (POST), Get Usernames & Media URL from Media_ID

### PR DESCRIPTION
**Pull request by Nikished**
Added features:
1. Blocking Instagram users (POST request).
2. Getting username by media ID.
3. Getting user info by name (with use case - appending user biography to media "caption" for further tag analysis).
4. Getting Instagram Media Url From Media_ID (using alphabet).

### CODE REVIEW

**Comment by Mishadow98** [comment]
Thank You!
But Where is all the info stored?

**Comment by Nikished** [comment]
We do not need to (or should not) store any user info locally. We get user biography by user name and append it to media caption only for the purpose of user filtering - we don't want to like business and spam accounts. Therefore, my version of instabot.py (when using the whole instabot in mode 0 with a large tag_blacklist) provides tools for additional user filtering to collect the target audience.

**Comment by Mishadow98** [comment]
Thank you Nikished. Very helpful

**Comment by ugurozturk** [comment]
Program already getting the url and owner id self.media_by_tag[i]['code'] and owner id self.media_by_tag[i]['owner']

**Comment by Nikished** [comment]
I agree about self.media_by_tag[i]['code'], but username and self.media_by_tag[i]['owner'] are not the same. I needed to get the first.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Pull request closed without merging**
