### PR TITLE
Heroku setup

### PR DESCRIPTION
**Pull request by ishalyminov**
A working Heroku solution:

* please see README_Heroku.md for a quick start
* some of the bot's arguments moved to env variables (=Heroku config vars)
* upon each unhandled exception, an email is sent

Please tell me if this is needed.

### CODE REVIEW

**Comment by ChipWolf** [comment]
Could you rip out the SMTP sender and use the actual Heroku logging specs please? https://devcenter.heroku.com/articles/logging

You can set up Logentries for alerting

**Comment by ishalyminov** [comment]
@ChipWolf done

**Comment by ishalyminov** [comment]
Please note that I moved tags to follow to the env file as well.
Although it's not related to Heroku, it may be thought of as private information (just like username and password), so this will help to keep users from committing it.

It also makes sense to move all the bot's config parameters to a separate file. And if this file is in e.g. ConfigObj format, it may be used in both Heroku and local setups.

**Comment by ishalyminov** [comment]
bump
All ok here or something else needed?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by callum8004** [comment]
@ishalyminov @ChipWolf did this heroku setup ever get deployed?

**Comment by callum8004** [comment]
Like to see the setup documentation if you still have it? Looking to follow the route of having it deployed to Heroku rather than on my raspberry pi.

**Pull request closed without merging**
