### PR TITLE
keywords feature

### PR DESCRIPTION
**Pull request by alexowson**
Added keywords filter to instabot.py and run.py

`keywords [str]: Words to use for finding profiles with username or biography contain these words`

Disabled if left null.

### CODE REVIEW

**Comment by dimisdas** [comment]
@maxatbrs @alexowson 

I have made some really minor changes, let me know if you can if everything works fine for you. I edited your PR to include some details.

I have one concern about the explanation in README:

> Words to use for finding profiles with username or biography contain these words

I can already see people wondering why the bot is not following anyone. It should be made more clear that this is a **filter**, and it doesn't seek people with these details actively. The bot fetches people from the hashtags and locations provided. In my humble opinion, that should also be reflected in run.py.

Thank you for your contribution! 💯

**Comment by alexowson** [comment]
Changes look good. 
About the explanation in README, you are free to change. 
Thanks for accepting my PR ✌🏻

**Comment by maxatbrs** [comment]
Looks good to me. Agree about the readme stuff!

**Comment by dimisdas** [comment]
Hello,

Unfortunately there are conflicts pending resolution. We merged a big pr and bumped the version number. Do you think you'd be able to resolve them so I can merge this? Thanks!

**Comment by alexowson** [comment]
Sure. Give me some time

**Comment by ohld** [comment]
LTGM! Great job!

**Comment by alexowson** [comment]
> Hello,
> 
> Unfortunately there are conflicts pending resolution. We merged a big pr and bumped the version number. Do you think you'd be able to resolve them so I can merge this? Thanks!

Done!

**Comment by yurilaaziz** [comment]
I rebased it to master 
could you please confirm the good behaviour please

**Pull request closed without merging**
