### PR TITLE
Feature: unfollow_count handled properly, follow_time parameter used

### PR DESCRIPTION
**Pull request by ivanchalov**
This update mainly does:
1. Makes sure unfollow_count increases in follows_db when account is unfollowed
2. Does not unfollow users that were already unfollowed on cleanup
3. Minor big fixes (details below)

Based on bug fixes from my Pull Request #1719 

Changes by file: 

a. src/sql_updates.py:
    1. Minor bug fix: on re-creation of usernames table, old username column is copied into new username column (instead of username_id - wrong)
    2. New function defined: check_already_unfollowed - it checks whether there is user_id with unfollow_count > 0 in follows_db

b. src/instabot.py: 
    1. cleanup function: when unfollowing on cleanup - it checks whether the user was already unfollowed and does not unfollow again if it was
    2. cleanup function bugfix: changed "for f in self.bot_follow_list:" into "for i in range(len(self.bot_follow_list)):" because the former combined with "self.bot_follow_list.remove(f)" results in only half of the list being iterated over
    3. unfollow function: now increases unfollow_count when successfully unfollowing user
    4. unfollow_on_cleanup function: now increases unfollow_count when successfully unfollowing user
    5. auto_unfollow function: removed call for insert_unfollow_count function as it is done now from unfollow function

c. src/new_unfollow.py:
    1. new_unfollow function: now increases unfollow_count when successfully unfollowing user

### CODE REVIEW

**Comment by ivanchalov** [comment]
I have submitted one more commit. It does the following:

0. Seems JSON format changed again, the first parsing parameter is not "activity_counts" any more! I have taken solution from nearby thread #1722 - thanks!

1. Added function get_username_to_unfollow_random into sql_updates.py: gets random user to unfollow which is older than follow_time parameter and has unfollow_count = 0
2. auto_unfollow now uses this function get_username_to_unfollow_random - so it will be auto unfollowing only users which are older than follow_time (previously parameter follow_time was not used anywhere)
3. auto_unfollow now handles users that were deleted and there is no page anymore, it looks like there is plenty of them!

**Comment by notmanhpham** [comment]
everything works for python 2.7 👍

**Comment by theinfinityproject** [comment]
Auto unfollow still seems to be bugged

` ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/pi/bot/instabot.py/src/instabot.py", line 898, in auto_unfollow
    user_info = all_data['graphql']['user']
KeyError: 'graphql'
`

**Comment by ivanchalov** [comment]
That's strange as this line is inside the try: block. If there is an error, it would not unfollow but won't crash..

Also, seems all_data json is loading. You can dump it into file with something like

```
def dump_json_into_file(json_data, filename):
    with io.open(filename, 'w', encoding='utf8') as outfile:
        str_ = json.dumps(json_data,
                          indent=4, sort_keys=False,
                          separators=(',', ': '), ensure_ascii=False)
        outfile.write(str(str_))
    return outfile.closed
```
And show here what's inside..

**Comment by theinfinityproject** [comment]
> 
> 
> That's strange as this line is inside the try: block. If there is an error, it would not unfollow but won't crash..
> 
That is exactly whats happening
> Also, seems all_data json is loading. You can dump it into file with something like
> 
> ```
> def dump_json_into_file(json_data, filename):
>     with io.open(filename, 'w', encoding='utf8') as outfile:
>         str_ = json.dumps(json_data,
>                           indent=4, sort_keys=False,
>                           separators=(',', ': '), ensure_ascii=False)
>         outfile.write(str(str_))
>     return outfile.closed
> ```
> 
> And show here what's inside..
I can do that alltho i need more precise instruction how to do it since my knowledge with linux and python is limited.

**Comment by ivanchalov** [comment]
> That is exactly whats happening. It dosnt crash but it dosnt unfollow either. Still it writes an error.log entry.

Do you have this code on top of the line where it crashes?
```
if r.text.find('The link you followed may be broken, or the page may have been removed.') != -1:
    log_string = "Looks like account was deleted, skipping : %s" % current_user
    self.write_log(log_string)
    insert_unfollow_count(self, user_id=current_id)
    time.sleep(3)
    return False
```

You might be trying to unfollow deleted accounts. I have fixed this in the latest commit.
If you don't have that code - please clone from the latest version.

**Comment by theinfinityproject** [comment]
> 
> 
> > That is exactly whats happening. It dosnt crash but it dosnt unfollow either. Still it writes an error.log entry.
> 
> Do you have this code on top of the line where it crashes?
> 
> ```
> if r.text.find('The link you followed may be broken, or the page may have been removed.') != -1:
>     log_string = "Looks like account was deleted, skipping : %s" % current_user
>     self.write_log(log_string)
>     insert_unfollow_count(self, user_id=current_id)
>     time.sleep(3)
>     return False
> ```


Yes I did. But i had some other commits merged into it aswell. So I cant say for sure what caused it. I hard reseted to master and only merged 1721, 1722. So far its looking good. Alltho my bot will start to unfollow 12h from now. So i cant say for sure yet. Gonna report tmrw

**Comment by nachovoss** [comment]
hey mate where is the file for the download of the new update?

**Comment by nachovoss** [comment]
> hi.
> still got the same problem
> C:\Users\Le_Nazareen\Documents\instabot\instabot.py-master>python example.py
> Traceback (most recent call last):
> File "example.py", line 6, in 
> from src import InstaBot
> File "C:\Users\Le_Nazareen\Documents\instabot\instabot.py-master\src__init__.py", line 1, in 
> from .instabot import InstaBot
> File "C:\Users\Le_Nazareen\Documents\instabot\instabot.py-master\src\instabot.py", line 840
> username_row = get_username_to_unfollow_random(self) if not username_row:
> ^
> IndentationError: expected an indented block
> 
> any ideas ? i'm just loosing my hairs !! :-(

wrong indentation, make sure the number spaces from the left edge of the script pages is right in that line

**Comment by uvedhe** [comment]
Fixed the problem, and it currently seems to work well, except that I see no changes to the actual Instagram account! It doesn't seem to follow any of the accounts that it says it is starting to follow (Can't verify the liking of media as I cannot convert the media id to a URL)

**Pull request merged**
