### PR TITLE
Fix 403 Error

### PR DESCRIPTION
**Pull request by jarosenthal**
This should fix the csrf error. The issue with the other PR is that he did not remove the old set code

### CODE REVIEW

**Comment by tylerko** [comment]
Thank you so much.
I got a lot of stress from 403 error.
It works really well after changing code thanks to you.

**Comment by damnitrahul** [comment]
Thank You. It works now.

**Comment by jinnishdalal** [comment]
can someone help me out with what to do to fix the error 403

**Comment by jarosenthal** [comment]
Copy the instabot.py file from this pull request into your src folder.

**Comment by macjaack** [comment]
Thank you, as soones I replied to your message I realized how to solve this problem, anways sorry for taking your time...

**Comment by jarosenthal** [comment]
Closing this in favor of #1503

**Comment by jinnishdalal** [comment]
after changing the instabot.py file i am getting this 


Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Jinnish Dalal\Documents\ig bots\instabot.py-master(vinesha.xx)\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\Jinnish Dalal\Documents\ig bots\instabot.py-master(vinesha.xx)\src\instabot.py", line 302, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Jinnish Dalal\Documents\ig bots\instabot.py-master(vinesha.xx)\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by jarosenthal** [comment]
@jinnishdalal seems there was another new error. Check out #1503

**Comment by mactrash** [comment]
@jarosenthal 
copy file from 
9f6a284

Still 403

**Comment by mactrash** [comment]
@jarosenthal May 403 error is still if I using l:locationid  tag can you take a look and fix thanks

**Comment by juguntert** [comment]
This only unfollows when I interrupt the bot with ctrl+c... How do I get it to unfollow in the middle of the regular actions?

**Comment by Jwalking26** [comment]
felt like a coder for all these mistakes. Thank you, guys! Much love.

**Comment by MediaGod** [comment]
@jarosenthal You're a FVCKING boss :)

**Comment by sjamod9** [comment]
Hello @jarosenthal this is working on Ubuntu but not on Mac, can you please check?

**Comment by lucaasleaal** [comment]
working but stop at the first like

**Comment by saily89** [comment]
can someone please help me? I saved the file with the changes to overwrite the old one but I am still gettin the 403 not liked error =(

**Pull request closed without merging**
