### PR TITLE
Adds standard requirements.txt file for project's dependencies

### PR DESCRIPTION
**Pull request by unformatt**

### CODE REVIEW

**Comment by ChipWolf** [comment]
Stick it in the root of the repository and I'll merge

**Comment by ChipWolf** [comment]
I'll get to this later, no need for a PR. Thanks.

**Comment by unformatt** [comment]
> Stick it in the root of the repository and I'll merge

See the files I changed. I've added the requirements.txt in this PR already.

> I'll get to this later, no need for a PR. Thanks.
I can't see a reason to not merge the PR. I've already done the work, which only took a minute.

**Comment by ChipWolf** [comment]
https://github.com/instabot-py/instabot.py/pull/348#issuecomment-290847235

**Comment by unformatt** [comment]
Got it - done! But I think you have to re-open the PR for it to update "Files Changed". You can see the change here: https://github.com/unformatt/instabot.py/tree/patch-1

**Comment by unformatt** [comment]
I pushed to the `patch-1` branch - same branch as this PR. 

Anyone can push to the branch to update a PR - I've never seen a different email address or user make a difference in the PR updating.

**Pull request merged**
