### PR TITLE
Keep a database with followers (no duplicated followers this way) v2

### PR DESCRIPTION
**Pull request by nivong**
cleaned up. Feel free to fork.
Ps I did no test it.
ref: https://github.com/instabot-py/instabot.py/pull/386

### CODE REVIEW

**Comment by stephenhyde** [comment]
@nivong if i run multiple instances of bot with different Instagram profiles, will they be pulling from the same list of usernames? that what it seems like from a quick audit of code, looks like a single column table with username. 

Suggestion would be to add an extra column where the username of the person running bot is used in conjunction with the media username liked

**Comment by nivong** [comment]
@stephenhyde  Be my guest to fork it and edit it ;)

**Comment by stephenhyde** [comment]
Ahaha already doing so

**Comment by 1mahdimf** [comment]
line 624
    except:
          ^
IndentationError: unindent does not match any outer indentation level

**Comment by 1mahdimf** [comment]
```
    unfollow_whitelist=['testxxx', 'test2xxx'])
  File "/instabot.py/src/instabot.py", line 206, in __init__
    self.login()
  File "/instabot.py/src/instabot.py", line 280, in login
    ui.get_followers()
  File "/userinfo.py", line 92, in get_followers
    r = json.loads(followers.text)
  File "/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ChipWolf** [comment]
@stephenhyde please merge it upstream when you're ready!

**Comment by RafaelCartenet** [comment]
I'm confused about this function working. It was apparently said in #350 that the get_followers() function was not working anymore. I tried it and got the same annoying JSON decoding issue mentioned just above. Any clue @ChipWolf ? Thanks in advance

**Comment by ChipWolf** [comment]
@RafaelCartenet I commented out lines 280 to 285 in `instabot.py` and removed the extra space from line 624

**Comment by ChipWolf** [comment]
I think a relational DB might be a bit excessive for this use case.
Pickle throwing the array into file would be more than sufficient.

**Comment by ChipWolf** [comment]
@nivong still didn't resolve the issue:

**Comment by RafaelCartenet** [comment]
@ChipWolf Thanks for your reply.
Regarding @nivong's issue to me it doesn't seem to be an issue, you'll keep trying to follow a guy until you manage to do so or until the like mode goes on and change the media. You'll still follow / comment / likes as many times.
Would be awesome to be able to have a get_followers() method again tho. No clue?

**Comment by ChipWolf** [comment]
@RafaelCartenet, yeah; then we can revert back to a stateless model.
I'd prefer to keep the fault tolerance though.

The entire project needs a major refactor, I'd like to package it as a PyPI package soon.

**Comment by MrJur1** [comment]
any news on this?

**Comment by ugurozturk** [comment]
Any news ?? looking forward for it, tried to edit myself but failed dont know python very well

**Comment by ugurozturk** [comment]
implemented it via a lot of new works

**Pull request closed without merging**
