### PR TITLE
support new instagram json structure

### PR DESCRIPTION
**Pull request by apdmatos**
Instagram release a new site api version with a new json structure. This PR will fix the bot to work with the new structure

### CODE REVIEW

**Comment by parkgrrr** [comment]
Is there a reason this isn't merged?  It's been broken for a while now, and I would love to just pull master instead of one of these other PR branches.

**Comment by ugurozturk** [comment]
@parkgrrr if you change your mind you are welcomed at https://github.com/ugurozturk/instabot.pyV2

**Comment by pablosproject** [comment]
@ugurozturk Instead of driving people to your repo, why not proposing yourself as maintainer of the actual one? I like your ideas and I think all can benefit

**Comment by ugurozturk** [comment]
@pablosproject well i sent 2 pr with new features. Waited for months. Then i did create new repo, im editing as my wish and helping in it. If i see any owner in this repo i will also stop driving people.

**Comment by pablosproject** [comment]
I got your point, I opened a ticket on this topic, let's see if we can make things move forward. #875

**Comment by ChipWolf** [comment]
@ugurozturk submit a PR. We'll add you as a collaborator to this project if you'd like in the spirit of keeping everything in one place

**Comment by ChipWolf** [comment]
@pablosproject I entirely agree, I'm not sure why anyone would think that was a good idea. I haven't seen a PR from @ugurozturk yet

**Comment by pablosproject** [comment]
Great, thanks a lot!

**Comment by ugurozturk** [comment]
@ChipWolf keeping everything in one place is the best idea. Im going to contact you about my ideas and the details of my fork

**Pull request merged**
