### PR TITLE
Following/unfollowing persistence - updated

### PR DESCRIPTION
**Pull request by uuaing**
To make this change simplify I resent this PR. It can be safely merge now.

Basically, I added a simple solution to restore users that we have followed/unfollowed to a sqlite3 database, so we can fix the duplicate following issue, the simple logic of this implement is we will not following a specific user more than twice which we have followed or unfollowed the account.

The only code break was in new_auto_mod_unfollow(), and I don't think the currently code is correct, you can see it make unfollowing for all followed in the bot_follow_list within one loop, so the self.unfollow_delay check is no use.

Currently I'll pick up one item from database that I think it should be, I'll hold the followed user in my following list for at least one day, I don't want to following/unfollowing for a specific use too frequently.
I also change some code in cleanup() as now we have following data restored so we can make the unfollowing work next time.

### CODE REVIEW

**Comment by ChipWolf** [comment]
#386

**Comment by stephenhyde** [comment]
Are you still planning on getting this merged @uuaing ? Data persistence would be a great thing for this bot as I don't want to unfollow users that were originally followed or duplicate follows.

**Comment by uuaing** [comment]
@stephenhyde Also you can safely merge https://github.com/instabot-py/instabot.py/pull/621/commits/692df25e352421266c97be8ac2e41b283cb2d577 to current branch by you  r own.

**Comment by stephenhyde** [comment]
@uuaing I was able to integrate your solution quite easily, I changed it slightly to accommodate multiple instances with different usernames. One question, I noticed after 24 hours you start unfollowing. Have you tested this out and did instagram give you any grief? Just worried that if i follow 555 users one day, the next day i unfollow 555 users and follow 555 users and so forth, will that raise any suspicions ?

**Comment by uuaing** [comment]
If the users didn't follow me over 24hour(I followed them), I'll unfollow
them, also I keeps the user that follows me for 10days, I have running my
bot over a month, got no banned so far.


2017年8月1日 上午10:14，"Stephen Hyde" <notifications@github.com>写道：

**Pull request closed without merging**
