### PR TITLE
[1287] Attempt to use regex to extract CSRF token

### PR DESCRIPTION
**Pull request by guido-n**
Attempted fix for issue #1287

### CODE REVIEW

**Comment by ValBerthe** [comment]
That seems great to me. Should'nt break anything important ; you could also comment something here just to mention the changes made and that would be perfect 👍

**Comment by guido-n** [comment]
Ok so basically the CSRF token is placed inside some javascript within the page, as opposed to a cookie in the HTTP response, when doing the first GET request. Hence the idea to extract it from the response body text.

The CSRF token is necessary otherwise the instagram public HTTP endpoints will respond with 403.

**Comment by twont** [comment]
You need to remember to add

Import re

at the top of the instabot.py file!

**Comment by abenasker** [comment]
works well : please merge

**Comment by focamonca** [comment]
I'm still having problems after this patch: 
http://prntscr.com/jqk6kb

**Comment by tux2000** [comment]
Works nicely, should be merged to the main branch asap.

**Comment by tux2000** [comment]
Works nicely, should be merged to the main branch asap.

**Comment by Sprellex** [comment]
How can i download the changes?

**Comment by iamgn10** [comment]
I copied the entire the instabot.py

**Comment by joaocpereiraa** [comment]
@guido-n  the fix work just for likes, for coments and follow the error continue... any idea?

**Comment by uglyeoin** [comment]
It seems to work intermittently for me.

**Comment by spaarkly** [comment]
This fix doesn't work anymore.

**Comment by protradingclub** [comment]
Having the same issue as well when trying to use the bot with a proxy 

```raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"```

**Comment by blackzafiqz** [comment]
not working

**Comment by osa1282** [comment]
not working

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=[])
  File "/root/instabot.py/src/instabot.py", line 234, in __init__
    self.login()
  File "/root/instabot.py/src/instabot.py", line 285, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by joaocpereiraa** [comment]
@uglyeoin can u send your files pls

**Comment by joaocpereiraa** [comment]
And anyone know why the bot always loop *get media from* after liked a photo

And after 10/15 minutes, sometimes less, starting to say *removing already liked medias*

**Pull request closed without merging**
